name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    name: Hello-Explore-GitHub-Actions-Geetha
    runs-on: ubuntu-20.04
    steps:
    - name: git clone
      run: echo "clonign repo"
    - name: runnin-test
      run: echo "doing test-cases"
    - name: checking-os version
      env: 
        name: "chaithanya"
      run: |
       cat /etc/os-release*
      if: $name  == "chaithanya" 
    
    
