name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
    - run: echo "heelo-chaitu"
  Explore-GitHub-Actions1:
    runs-on: self-hosted
    steps:
    - run: |
       echo "hello-chaitu"
       echo "hello-chaitu123"
  Printing-Env:
     runs-on:  self-hosted 
     steps:
     - run: env
    
    
