name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    name: Hello-Explore-GitHub-Actions-Geetha
    runs-on: self-hosted
    environment: Project1
    steps:
     - name: sleeping
       run: sleep 10s
       timeout-minutes: 1
     - run: echo "This is second -step"  
    

