name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    name: Hello-Explore-GitHub-Actions-Geetha
    runs-on: self-hosted
    steps:
     - name: Printing
       run: echo "This is MY_NAME_IS - ${{ vars.MY_NAME_IS }}"
    
